### ISSUE TITLE
Problems with .addLeaf()

### ISSUE THREAD

**Issue by AlgebraicFloat** [simpleclub/math_keyboard#42]
## Bug description

*When trying to add fractions into the mathtextfield they end up giving a parser error after trying to edit*

### To Reproduce

_mathController.addLeaf(r"\frac{1");
_mathController.addLeaf("2");
_mathController.addLeaf("}{3");
_mathController.addLeaf("4");
_mathController.addLeaf("}");
_mathController.addLeaf("");

try editing the fraction using the math keyboard.

## Expected behavior

It would be great if you could add fractions into the mathfield by using addLeaf(). Maybe I'm just not looking in the right places for this functionality.

"Parser Error: Expected '}', got 'EOF' makes sense since I'm deleting the bracket, but how do I make the fraction editable in the mathtextfield?

**Comment by edhom** [comment]
Hi @AlgebraicFloat, please have a look at `addFunction()` for everything that takes arguments (e.g. like fractions do)🙂
