### ISSUE TITLE
Breaking change, update intl to 0.18.1.

### ISSUE THREAD

**Issue by rsegecin** [simpleclub/math_keyboard#51]
## Bug description

math_keyboard package won't run with newest flutter sdk. 

see error below:
    
    [flutter_lib_test] flutter pub get
    Resolving dependencies...
    Because math_keyboard >=0.0.1 depends on flutter_localizations from sdk which depends on intl 0.18.1, math_keyboard >=0.0.1 requires intl 0.18.1.
    So, because flutter_lib_test depends on math_keyboard ^0.1.9 which depends on intl ^0.17.0, version solving failed.
    exit code 1

### To Reproduce

1. create a flutter app on the latest Flutter 3.10 sdk.
2. add `math_keyboard: ^0.1.9` as dependency package.
3. run `flutter pub get`
4. see error.

Updating math_keyboard's intl package dependency to 0.18.1 should solve the issue.

**Comment by edhom** [comment]
Fixed with math_keyboard 0.2.0
